### ISSUE TITLE
Improvement to App Lock List (sorted, only apps etc.) (blacklist)

### ISSUE THREAD

**Issue by leonpoint** [FHellmann/Uniatron#31]
We should improve the app lock list. It should
- be sorted alphabetically
- only include Apps, not services
- inform the user that blocking 'Uniatron' will stop him from editing App locks or trading his steps if the app use time ran out. This will force the user to **uninstall** the app.
- not show essential / emergency services and apps, such as the Telephone, Emergency Mode, etc.
- (show blocked apps at the beginning of the list)
#

**Comment by FHellmann** [comment]
I have to agree with you in most of your points.

- The third one will never happen, because our own app 'Uniatron' is not shown in the list. It is already filtered before.
- I have no idea how to filter essential /emergency services/apps yet. Open for any ideas.

**Comment by leonpoint** [comment]
We might be able to filter out preinstalled apps (This will remove YouTube though, and Facebook on some devices)? 
-> We could then manually add the most common social apps out there. It's not the cleanest workaround but might work.

**Comment by FHellmann** [comment]
Exactly... It is possible to query all the apps the user installed by himself. This excludes all system and pre-installed apps (e. g. YouTube).
But sure, we can include these apps with a configuration of our own.

**Comment by leonpoint** [comment]
@FHellmann issue almost fixed. 
1. The list should ideally refresh itself when the user checks / unchecks a box. I can't figure it out. Current state is https://github.com/FHellmann/Uniatron/commit/838f5ebb94ad99a5e5a807939e6181082764d1e3.
2. Getting a checkstyle violation in \uniatron\ui\setting\SettingViewModel.java
> Found 'UR'-anomaly for variable 'name' (lines '63'-'95')

I can't resolve it.. 🤔
