### ISSUE TITLE
App usage by blacklisted apps

### ISSUE THREAD

**Issue by FHellmann** [FHellmann/Uniatron#34]
**Describe the bug**
The app usage time for a specified time range is collected for all apps.

**Expected behavior**
The app usage time for a specified time range should be collectable only for the apps which are blacklisted.

**Possible solution**
- [x] Rename method to loadRemainingAppUsageTimeByBlacklist
- [x] Add method parameter: List<String> blacklist
- [x] Query only for entries which are contained in the blacklist parameter

In the AppUsageDao:
```java
    @Query("SELECT (SELECT TOTAL(time_in_minutes * 60) FROM TimeCreditEntity "
            + "WHERE timestamp BETWEEN :dateFrom AND :dateTo) - TOTAL(usage_time_in_seconds) "
            + "FROM AppUsageEntity WHERE timestamp BETWEEN :dateFrom AND :dateTo")
    LiveData<Integer> loadRemainingAppUsageTime(Date dateFrom, Date dateTo);
```

**Comment by anja-h** [comment]
Edit App usage time in history view
