### ISSUE TITLE
Blacklist chooser sometimes empty

### ISSUE THREAD

**Issue by FHellmann** [FHellmann/Uniatron#37]
**Describe the bug**
Sometimes the dialog for choosing the blacklist apps is empty. 

**To Reproduce**
This error comes up very flexible. For now it is not possible to reproduce the 

**Expected behavior**
The blacklist shows up all the installed apps all the time.

**Comment by leonpoint** [comment]
@FHellmann 
I found out a way to reproduce this bug:

1. Clear app from Taskmanager.
2. Open app, and have a look at the black list chooser. It should be displayed properly.
3. Swipe to the leftmost screen (history view)
4. Swipe to the settings screen and open blacklist chooser. It is now empty.

#### Tested on
Device: Galaxy S8. 
Android: 8.1
Commit: https://github.com/FHellmann/Uniatron/commit/11c4026d48b3471cf2cfe69d6cce58ad96a0179d
