### ISSUE TITLE
App updates from PlayStore trigger BlacklistAddNotification

### ISSUE THREAD

**Issue by leonpoint** [FHellmann/Uniatron#45]
**Describe the bug**
1. When updating any app from the PlayStore, the notification "Click here to add <xyz> to the blacklist" appears.
2. This also happens with all silent automatic updates (e.g. of the PlayStore app). 
Thus, the notification appears multiple times per week.

Is Nr. 1 intended?
Nr. 2 is fixed when Nr.1 is resolved.

**Comment by FHellmann** [comment]
I've already seen this behavior. This is the result of the PACKAGE_UPDATE event. The broadcast receiver should be unsubscribed on this event. This should lead to the wished behavior.

**Comment by leonpoint** [comment]
fixed in https://github.com/FHellmann/Uniatron/commit/a621a00950be153a9a1b746bf263c835e675711d
