### ISSUE TITLE
Notification spam

### ISSUE THREAD

**Issue by FHellmann** [FHellmann/Uniatron#94]
**Describe the bug**
The notification for upcoming time pops up multiple times with the same message.

**Expected behavior**
The notification should pop up only once.

**Screenshots**
![img-20180804-wa0002](https://user-images.githubusercontent.com/5815289/43676155-b84e1d96-97eb-11e8-8159-7f9a02b5cc1b.jpg)

**Comment by speedyhoopster3** [comment]
Tritt der Fehler auf wenn du genau bei 4:59 die app verlässt?

**Comment by FHellmann** [comment]
It looks like as this is the behaviour.
